channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
dependencies:
  - python==3.9.*
  - ipython
  - cmake
  - pybind11
  - pytorch
  - pytorch-cuda=11.8
  - pytorch3d
  - torchvision
  - torchaudio
  - pyg
  - pytorch-cluster
  - pytorch-scatter
  # - exa # optional: nice ls
  # - fzf # optional: fancy ctrl + R
  - pip
  - pip:
    - numpy # certain deprecated operations were used in other deps
    - scipy == 1.10.1
    - sentencepiece==0.1.99 
    - pandas==2.0.3
    # - sophuspy
    # - pybullet
    # - trimesh
    # - pytest
    # - scikit-image
    # - scikit-fmm
    # - scikit-learn
    # - numpy-quaternion
    # - natsort
    # - frozendict
    # # Robots
    - opencv-python
    # - pin>=2.6.17
    # # Neural networks
    - openai-clip
    - timm
    
    # - mss
    # # visualizations and debugging
    - matplotlib==3.7.2
    # # Command line tools
    # - click
    # # data tools
    # - yacs
    # - h5py
    - imageio
    # - pygifsicle
    # - pynput
    # - git+https://github.com/openai/CLIP.git
    - open3d
    - numpy-quaternion
    # # For MiDaS
    # - imutils

    # Navigation
    - more-itertools
    - pyliblzfse
    - einops
    - transformers
    - sentence-transformers
    - git+https://github.com/facebookresearch/detectron2.git
    - git+https://github.com/zhanghang1989/PyTorch-Encoding/
    - pytorch-lightning
    - wget
    - gdown
    - torch_geometric
    - tqdm
    # - git+https://github.com/facebookresearch/segment-anything
    - ninja
    

    # grasping
    - git+https://github.com/NVIDIA/MinkowskiEngine
    # - graspnetAPI
    - protobuf==3.19.0
    - git+https://github.com/luca-medeiros/lang-segment-anything.git




